logging:
  level: INFO

  appenders:
    - type: console
      threshold: ALL
      timeZone: IST

server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    port: 2000
    type: https

database:
  driverClass: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://127.0.0.1:3306/temp?autoReconnect=true&useSSL=false
  user: root
  password: "Fk!@#%213501"
  maxWaitForConnection: 1s
  validationQuery: "SELECT 1"
  validationQueryTimeout: 3s
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute
  checkConnectionOnBorrow: true